kind: ConfigMap
apiVersion: v1
metadata:
  namespace: nuntapong
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        default_type
        application/json;
        return 200 "nuntapong siripanyawong";
      }
    }